default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: shine
  password: shine
  pool: 5

development:
  <<: *default
  database: shine_development

test:
  <<: *default
  database: shine_test

production:
  <<: *default
  database: shine_production
  username: shine
  password: <%= ENV['SHINE_DATABASE_PASSWORD'] %>
