# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ff8bd3d52a42d9d94df438de113760a44a75e7448b756fe1fb5af62e08b462ac426f7e6c25a414e7b10449a1754c4d6b093f89ef7d200d36abd698a028f2bf1

test:
  secret_key_base: 058ad1332eaf2ea6b8bc0dd17d033d05eed353a52fbfbc37448ccec44dd834a35eacefdd56275e75af5ddb69bd2a2f27a2160a54d22500fc77567d7a5c678abc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
